### ISSUE TITLE
Update typeface to match logo typeface

### ISSUE THREAD

**Issue by arelia** [promptconf/promptconf.github.io#20]
@sunahsuh what is the logo typeface?

**Comment by arelia** [comment]
logo in Canva is here: https://www.canva.com/design/DADWyOspPOM/share/preview?token=GPE4NAriQbrq4o0olRoeNw&role=EDITOR&utm_content=DADWyOspPOM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Font is here: https://fontlibrary.org/en/font/kawkab-mono#Kawkab%20Mono-Light

Will need to add attribution maybe - http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#2855b85f

**Comment by arelia** [comment]
Logo typeface/Kawkab (left) vs Roboto (right)

<img width="1680" alt="Screen Shot 2019-05-28 at 8 09 05 PM" src="https://user-images.githubusercontent.com/2359538/58522129-965f3980-8184-11e9-8224-0c92312cd9c2.png">

Using Kawkab as a headline typeface

<img width="1679" alt="Screen Shot 2019-05-28 at 8 08 45 PM" src="https://user-images.githubusercontent.com/2359538/58522157-aaa33680-8184-11e9-902e-4b8051fffdee.png">

**Comment by sunahsuh** [comment]
Per slack, we're leaving the font for both text and headers as Roboto!
