### ISSUE TITLE
Post-Conference Website Update

### ISSUE THREAD

**Issue by lorenanicole** [promptconf/promptconf.github.io#60]
# Overview

PromptConf 2019 now over means we need to start prepping the website for PromptConf 2020! In prep for that we'll need to ...

## Scope of work

- [ ] Find any outdated data that needs to be updated, please enumerate pages that need updates below:
      - [ ] 
      - [ ] 
- [ ] Prepare the website for our forthcoming blog updates (e.g. COC transparency report)
- [ ] Whatever else

**Comment by arelia** [comment]
fixed by #63
